# Generated by Django 3.1 on 2020-09-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200901_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.IntegerField(blank=True),
        ),
    ]
