# Generated by Django 3.1 on 2020-09-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200901_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='boxOffice',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbVotes',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
