# Generated by Django 3.1 on 2020-09-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200902_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Poster_url',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
