# Generated by Django 3.1 on 2020-09-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movie', '0011_auto_20200904_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(blank=True, to='actor.Actor'),
        ),
    ]
