# Generated by Django 3.1 on 2020-09-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Trash'), (2, 'Horrible'), (3, 'Terrible'), (4, 'Bad'), (5, 'OK'), (6, 'Watchable'), (7, 'Good'), (8, 'Very good'), (9, 'Perfect'), (10, 'Master Piece')]),
        ),
    ]
