# Generated by Django 3.1 on 2020-09-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_auto_20200904_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together={('name', 'slug')},
        ),
    ]
