# Generated by Django 3.1 on 2020-09-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_auto_20200904_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
