# Generated by Django 3.1 on 2020-09-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_auto_20200904_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together=set(),
        ),
    ]
