# Generated by Django 3.1.1 on 2020-09-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_auto_20200908_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
